Aligned the last breadcrumb with others #71
Space2Study-UA-1156/Client-02 pull request #110
Opened 2024-04-26 17:56 UTC by Olenka-Hryk

Aligned the last breadcrumb with others: Close #71 

**Before alignment changes:**
<img width="339" alt="Screenshot 2024-04-26 at 20 25 28" src="https://github.com/Space2Study-UA-1156/Client-02/assets/28622400/d8379444-a75f-4035-9286-6d7808e87076">

**Received the result after the changes:**
<img width="339" alt="Screenshot 2024-04-26 at 20 39 29" src="https://github.com/Space2Study-UA-1156/Client-02/assets/28622400/2e0d809c-cf60-4179-8deb-46dab7a51980">

2024-04-26 18:28 UTC, docia approved these changes

2024-04-26 18:46 UTC, ohanovdmytro approved these changes

2024-04-27 09:56 UTC, BodiaPutiak approved these changes

2024-04-29 06:54 UTC, vlad-khrychov requested changes

2024-04-29 06:54 UTC, vlad-khrychov commented on src/containers/layout/app-breadcrumbs/AppBreadCrumbs.styles.js
> +      display: 'block'
Not clearly why style for `a` is working) Last element is link, maybe you should write (change) styles for `link`?

2024-04-29 17:58 UTC, vlad-khrychov approved these changes

2024-04-30 12:21 UTC, merged