(SP: 1) Write unit test for "PopupDialog" component
Space2Study-UA-1156/Client-02 pull request #117
Opened 2024-04-28 16:16 UTC by docia

Implemented the following testing for "PopupDialog" component: 

 - Content text should be shown
 - Imitate click on the close button and popup should be closed
 - Imitate click with delay and popup should be closed

<img width="656" alt="Screenshot 2024-04-28 at 19 14 54" src="https://github.com/Space2Study-UA-1156/Client-02/assets/102433497/587f81b8-fc27-49ad-a018-a4f72d74619a">

2024-04-29 12:44 UTC, Olenka-Hryk approved these changes

2024-04-29 12:51 UTC, m6xcom approved these changes

2024-04-29 13:17 UTC, Nazar-Lysak approved these changes

2024-04-30 17:42 UTC, docia commented
@vlad-khrychov coverage is 83.33, although all lines are covered: 
![image](https://github.com/Space2Study-UA-1156/Client-02/assets/102433497/d85c6552-cc03-444e-a13f-9a1be4f763fd)

I would be grateful if you could give a hint or advise how to understand why the coverage is not 100 and where to search for hints in the future.

2024-04-30 18:50 UTC, Olenka-Hryk approved these changes

2024-04-30 18:56 UTC, Olenka-Hryk approved these changes

2024-05-01 12:45 UTC, vlad-khrychov requested changes
We have an error in the console that "setNeedConfirmation is not a function", so the `use-confirm` mock doesn't work properly. And look at the coverage when we run just this test.
![image](https://github.com/Space2Study-UA-1156/Client-02/assets/67462207/3a9cdc85-e1ba-41e2-8f1e-dd87cf60303d)
![image](https://github.com/Space2Study-UA-1156/Client-02/assets/67462207/c56282fb-3ddc-4804-b919-6d0952422389)
This means that these files have also been run.

2024-05-01 12:45 UTC, vlad-khrychov commented on tests/unit/components/popup-dialog/PopupDialog.spec.jsx
> +      }
mocks should be on top level of test file.

2024-05-06 10:45 UTC, BodiaPutiak approved these changes

2024-05-06 10:55 UTC, vlad-khrychov approved these changes

2024-05-06 12:15 UTC, merged