(SP: 1) Write unit test for "Subjects" page #101
Space2Study-UA-1156/Client-02 pull request #120
Opened 2024-04-29 15:44 UTC by Nazar-Lysak

![image](https://github.com/Space2Study-UA-1156/Client-02/assets/76834306/29c5141c-e04a-4c75-9347-12f3f6c7ccbd)

2024-04-30 14:30 UTC, m6xcom approved these changes

2024-04-30 18:23 UTC, docia commented
- It should render page - done by your test. 
- Text of the page must be in the document - NOT done. I'd advise you to use 'getByText' and 'toBeInTheDocument' to check for the document's text.  
+ based on Vladyslav's comment on my task, it is also advisable to mock the PageWrapper component. 

@vlad-khrychov please give your opinion on my comment.

2024-04-30 18:25 UTC, docia reviewed
- It should render page - done by your test.
- Text of the page must be in the document - NOT done. I'd advise you to use 'getByText' and 'toBeInTheDocument' to check for the document's text.

+ based on Vladyslav's comment on my task, it is also advisable to mock the PageWrapper component.

@vlad-khrychov please give your opinion on my comment.

2024-04-30 18:49 UTC, Nazar-Lysak commented
Hi @docia ,
Thank you for your feedback. I agree and will update the test as you suggested

2024-04-30 18:59 UTC, docia approved these changes

2024-04-30 19:07 UTC, Olenka-Hryk approved these changes

2024-04-30 20:45 UTC, vlad-khrychov commented
Yes, if `PageWraper` mocked, you can use `test-id` in this mock. So, in the first test `getByTestId` will be used  and `getByText` will be used in second `it`.

2024-05-01 12:48 UTC, vlad-khrychov requested changes
Mock `PageWraper` and get mocked div by test id in the first test,

2024-05-02 18:44 UTC, vlad-khrychov approved these changes
Now it looks great!

2024-05-02 18:44 UTC, vlad-khrychov commented on tests/unit/pages/subjects/Subjects.spec.jsx
> +import { render, screen } from '@testing-library/react'
```suggestion
import { render, screen } from '@testing-library/react'
import { renderWithProviders } from '~tests/test-utils'
```

2024-05-03 06:10 UTC, merged