(SP: 1) Write unit test for "TitleWithDescription" component
Space2Study-UA-1156/Client-02 pull request #122
Opened 2024-04-29 16:58 UTC by Nazar-Lysak

![image](https://github.com/Space2Study-UA-1156/Client-02/assets/76834306/e2a64740-b480-4181-82a2-b5518ac9b526)

2024-04-29 19:17 UTC, docia approved these changes

2024-04-30 14:28 UTC, m6xcom approved these changes

2024-04-30 18:41 UTC, docia approved these changes

2024-04-30 23:09 UTC, Olenka-Hryk approved these changes

2024-05-01 10:52 UTC, vlad-khrychov requested changes

2024-05-01 10:52 UTC, vlad-khrychov commented on tests/unit/components/title-with-description/TitleWithDescription.spec.jsx
> +  })
I believe we can remove this test.

2024-05-01 10:52 UTC, vlad-khrychov commented on tests/unit/components/title-with-description/TitleWithDescription.spec.jsx
> +  test('should render TitleWithDescription component with title and description', () => {
```suggestion
  it('should render TitleWithDescription component with title and description', () => {

```

2024-05-02 07:40 UTC, BodiaPutiak approved these changes

2024-05-02 07:55 UTC, vlad-khrychov approved these changes

2024-05-02 16:32 UTC, merged