(SP: 1) Write unit test for "PageWrapper" component #94
Space2Study-UA-1156/Client-02 pull request #123
Opened 2024-04-30 14:26 UTC by m6xcom

![image](https://github.com/Space2Study-UA-1156/Client-02/assets/65496114/6787a33e-594c-4472-b069-65ad26cfad9e)

2024-04-30 16:18 UTC, Nazar-Lysak approved these changes

2024-04-30 18:37 UTC, docia approved these changes

2024-05-01 08:49 UTC, Olenka-Hryk approved these changes

2024-05-01 10:48 UTC, vlad-khrychov requested changes

2024-05-01 10:48 UTC, vlad-khrychov commented on tests/unit/components/page-wrapper/PageWrapper.spec.jsx
In `PageWrapper` we use `useModalContext`, so we should render it via `renderWithProviders`

2024-05-01 15:02 UTC, m6xcom commented on tests/unit/components/page-wrapper/PageWrapper.spec.jsx
fixed

2024-05-02 07:55 UTC, vlad-khrychov approved these changes

2024-05-02 08:36 UTC, merged