(SP: 1) Write unit test for "Tab" component
Space2Study-UA-1156/Client-02 pull request #125
Opened 2024-04-30 19:41 UTC by Nazar-Lysak

- Label of the tab should be rendered
-  Applies active tab if it is true
-  Does not apply active tab if it is false
-  Imitate click on the button and onClick function should be called

2024-05-01 07:47 UTC, docia approved these changes

2024-05-02 00:17 UTC, Olenka-Hryk commented on tests/unit/components/tab/Tab.spec.jsx
Please, could you reload the image of the coverage for this test?

2024-05-02 00:20 UTC, Olenka-Hryk commented on tests/unit/components/tab/Tab.spec.jsx
> +describe('Tab component test', () => {
Also, can you add these scenarios:
- [ ] Applies active tab if it is true
- [ ] Does not apply active tab if it is false

2024-05-03 06:15 UTC, m6xcom approved these changes

2024-05-03 12:21 UTC, BodiaPutiak approved these changes

2024-05-06 11:03 UTC, vlad-khrychov requested changes

2024-05-06 11:03 UTC, vlad-khrychov commented on tests/unit/components/tab/Tab.spec.jsx
> +describe('Tab component test', () => {
@Nazar-Lysak , I agree with @Olenka-Hryk  about adding a test with scenario "Does not apply active tab if `activeTab` prop is false"

2024-05-07 12:10 UTC, vlad-khrychov approved these changes

2024-05-07 12:26 UTC, merged