[Login popup] Login button is clickable
Space2Study-UA-1156/Client-02 pull request #86
Opened 2024-04-25 16:44 UTC by Nazar-Lysak

…word [Login popup] Login button is clickable without entering any data in Email and Password field

2024-04-25 16:46 UTC, docia approved these changes

2024-04-25 18:29 UTC, docia approved these changes

2024-04-25 18:35 UTC, m6xcom approved these changes

2024-04-26 11:16 UTC, ohanovdmytro approved these changes

2024-04-26 16:00 UTC, Olenka-Hryk reviewed
Do you check the Password field as well? Because according to the requirements, the Login button should be disabled until data is entered in both the Email and Password fields.

2024-04-26 16:13 UTC, vlad-khrychov requested changes
I agree with @Olenka-Hryk about password checking. Please add it too.

2024-04-29 12:38 UTC, Olenka-Hryk commented on src/containers/guest-home-page/login-form/LoginForm.jsx
> +  console.log()
Could you please remove the ```console.log()``` statement from this code?

2024-04-29 18:02 UTC, vlad-khrychov requested changes

2024-04-29 18:02 UTC, vlad-khrychov commented on src/containers/guest-home-page/login-form/LoginForm.jsx
> +    return emailValue?.length && data?.password?.length ? false : true
Look at comment from sonar 
![image](https://github.com/Space2Study-UA-1156/Client-02/assets/67462207/a80a535a-ac1e-407a-8765-9e5f87f0f070)
You can write smth like
```suggestion
    return !(emailValue?.length && data?.password?.length)
```

2024-04-30 05:20 UTC, vlad-khrychov approved these changes

2024-04-30 06:10 UTC, merged